{{- range $name, $config := .Values.vaultSecrets }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "vaultsecret") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  refreshPeriod: {{ default "1h" $config.refreshPeriod | quote }}
  refreshThreshold: {{ default 90 $config.refreshThreshold }}
  {{- if hasKey $config "syncOnResourceChange" }}
  syncOnResourceChange: {{ $config.syncOnResourceChange }}
  {{- end }}
  vaultSecretDefinitions:
    {{- required (printf "vaultSecrets.%s.vaultSecretDefinitions is required" $name) $config.vaultSecretDefinitions | toYaml | nindent 4 }}
  output:
    name: {{ required (printf "vaultSecrets.%s.output.name is required" $name) $config.output.name | quote }}
    type: {{ default "Opaque" $config.output.type | quote }}
    stringData:
      {{- required (printf "vaultSecrets.%s.output.stringData is required" $name) $config.output.stringData | toYaml | nindent 6 }}
    {{- with $config.output.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $config.output.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
