{{- range $name, $config := .Values.vaultSecrets }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "vaultsecret") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  refreshPeriod: {{ default "1h" $config.refreshPeriod | quote }}
  refreshThreshold: {{ default 90 $config.refreshThreshold }}
  {{- if hasKey $config "syncOnResourceChange" }}
  syncOnResourceChange: {{ $config.syncOnResourceChange }}
  {{- end }}
  vaultSecretDefinitions:
    {{- $auth := $config.authentication -}}
    {{- range $def := (required (printf "vaultSecrets.%s.vaultSecretDefinitions is required" $name) $config.vaultSecretDefinitions) }}
    - name: {{ required "vaultSecretDefinition.name is required" $def.name | quote }}
      authentication:
        path: {{ default "kubernetes" (default $auth.path ($def.authentication).path) | quote }}
        role: {{ default $auth.role ($def.authentication).role | quote }}
        serviceAccount:
          name: {{ default "default" (default ($auth.serviceAccount).name (($def.authentication).serviceAccount).name) | quote }}
        {{- with default $auth.namespace ($def.authentication).namespace }}
        namespace: {{ . | quote }}
        {{- end }}
      {{- with default $config.connection $def.connection }}
      connection:
        address: {{ .address | quote }}
        {{- with .maxRetries }}
        maxRetries: {{ . }}
        {{- end }}
        {{- with .timeOut }}
        timeOut: {{ . | quote }}
        {{- end }}
        {{- with .tLSConfig }}
        tLSConfig:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      path: {{ required "vaultSecretDefinition.path is required" $def.path | quote }}
      {{- with $def.requestType }}
      requestType: {{ . | quote }}
      {{- end }}
      {{- with $def.requestPayload }}
      requestPayload:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  output:
    name: {{ required (printf "vaultSecrets.%s.output.name is required" $name) $config.output.name | quote }}
    type: {{ default "Opaque" $config.output.type | quote }}
    stringData:
      {{- required (printf "vaultSecrets.%s.output.stringData is required" $name) $config.output.stringData | toYaml | nindent 6 }}
    {{- with $config.output.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $config.output.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
