---
nameOverride: ""
fullnameOverride: ""

randomSecrets: {}

vaultSecrets: {}

groups: {}

groupAliases: {}

entities: {}

entityAliases: {}

identityOidcProviders: {}

identityOidcScopes: {}

identityOidcClients: {}

identityOidcAssignments: {}

identityTokenConfigs: {}

identityTokenKeys: {}

identityTokenRoles: {}
