---

randomSecrets:
  ci-rs:
    authentication:
      role: vault-ci
    path: secret/ci
    secretKey: password
    # isKVSecretsEngineV2: false
    secretFormat:
      passwordPolicyName: default-password

quaySecretEngineConfigs:
  ci-quay:
    authentication:
      role: vault-ci
    path: quay
    url: "https://quay.example.com"

quaySecretEngineRoles:
  ci-quay-role:
    authentication:
      role: vault-ci
    path: quay
    namespaceName: my-org
    namespaceType: organization

quaySecretEngineStaticRoles:
  ci-quay-static:
    authentication:
      role: vault-ci
    path: quay
    namespaceName: my-org
