{{- range $name, $config := .Values.databaseSecretEngineRoles }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "dbrole") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "databaseSecretEngineRoles.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "databaseSecretEngineRoles.%s.path is required" $name) $config.path | quote }}
  dBName: {{ required (printf "databaseSecretEngineRoles.%s.dBName is required" $name) $config.dBName | quote }}
  name: {{ default $name $config.name | quote }}
  defaultTTL: {{ default "0s" $config.defaultTTL | quote }}
  maxTTL: {{ default "0s" $config.maxTTL | quote }}
  {{- with $config.creationStatements }}
  creationStatements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.renewStatements }}
  renewStatements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.revocationStatements }}
  revocationStatements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.rollbackStatements }}
  rollbackStatements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
