{{- range $name, $config := .Values.databaseSecretEngineStaticRoles }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineStaticRole
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "dbstaticrole") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "databaseSecretEngineStaticRoles.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "databaseSecretEngineStaticRoles.%s.path is required" $name) $config.path | quote }}
  dBName: {{ required (printf "databaseSecretEngineStaticRoles.%s.dBName is required" $name) $config.dBName | quote }}
  username: {{ required (printf "databaseSecretEngineStaticRoles.%s.username is required" $name) $config.username | quote }}
  rotationPeriod: {{ required (printf "databaseSecretEngineStaticRoles.%s.rotationPeriod is required" $name) $config.rotationPeriod }}
  name: {{ default $name $config.name | quote }}
  {{- with $config.credentialType }}
  credentialType: {{ . | quote }}
  {{- end }}
  {{- with $config.passwordCredentialConfig }}
  passwordCredentialConfig:
    {{- with .passwordPolicy }}
    passwordPolicy: {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- with $config.rsaPrivateKeyCredentialConfig }}
  rsaPrivateKeyCredentialConfig:
    {{- with .format }}
    format: {{ . | quote }}
    {{- end }}
    {{- with .keyBits }}
    keyBits: {{ . }}
    {{- end }}
  {{- end }}
  {{- with $config.rotationStatements }}
  rotationStatements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
