{{- range $name, $config := .Values.githubSecretEngineRoles }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "githubsecretenginerole") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "githubSecretEngineRoles.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "githubSecretEngineRoles.%s.path is required" $name) $config.path | quote }}
  {{- with $config.name }}
  name: {{ . | quote }}
  {{- end }}
  {{- with $config.installationID }}
  installationID: {{ . }}
  {{- end }}
  {{- with $config.organizationName }}
  organizationName: {{ . | quote }}
  {{- end }}
  {{- with $config.permissions }}
  permissions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.repositories }}
  repositories:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.repositoriesIDs }}
  repositoriesIDs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
