{{- range $name, $config := .Values.githubSecretEngineConfigs }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineConfig
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "githubsecretengineconfig") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "githubSecretEngineConfigs.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  applicationID: {{ required (printf "githubSecretEngineConfigs.%s.applicationID is required" $name) $config.applicationID }}
  gitHubAPIBaseURL: {{ default "https://api.github.com" $config.gitHubAPIBaseURL | quote }}
  path: {{ required (printf "githubSecretEngineConfigs.%s.path is required" $name) $config.path | quote }}
  {{- with $config.sSHKeyReference }}
  sSHKeyReference:
    {{- with .secret }}
    secret:
      name: {{ .name | quote }}
    {{- end }}
    {{- with .vaultSecret }}
    vaultSecret:
      path: {{ .path | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
