{{- range $name, $config := .Values.quaySecretEngineConfigs }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineConfig
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "quaysecretengineconfig") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "quaySecretEngineConfigs.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "quaySecretEngineConfigs.%s.path is required" $name) $config.path | quote }}
  {{- with $config.url }}
  url: {{ . | quote }}
  {{- end }}
  disableSslVerification: {{ ternary $config.disableSslVerification false (hasKey $config "disableSslVerification") }}
  {{- with $config.caCertificate }}
  caCertificate: {{ . | quote }}
  {{- end }}
  {{- with $config.rootCredentials }}
  rootCredentials:
    {{- with .usernameKey }}
    usernameKey: {{ . | quote }}
    {{- end }}
    {{- with .passwordKey }}
    passwordKey: {{ . | quote }}
    {{- end }}
    {{- with .secret }}
    secret:
      name: {{ .name | quote }}
    {{- end }}
    {{- with .vaultSecret }}
    vaultSecret:
      path: {{ .path | quote }}
    {{- end }}
    {{- with .randomSecret }}
    randomSecret:
      name: {{ .name | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
