{{- range $name, $config := .Values.quaySecretEngineStaticRoles }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineStaticRole
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "quaysecretenginestaticrole") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "quaySecretEngineStaticRoles.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "quaySecretEngineStaticRoles.%s.path is required" $name) $config.path | quote }}
  name: {{ default $name $config.name | quote }}
  {{- with $config.namespaceName }}
  namespaceName: {{ . | quote }}
  {{- end }}
  namespaceType: {{ default "organization" $config.namespaceType | quote }}
  createRepositories: {{ ternary $config.createRepositories false (hasKey $config "createRepositories") }}
  {{- with $config.defaultPermission }}
  defaultPermission: {{ . | quote }}
  {{- end }}
  {{- with $config.repositories }}
  repositories:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.teams }}
  teams:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
