{{- range $name, $config := .Values.rabbitmqSecretEngineRoles }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RabbitMQSecretEngineRole
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "rabbitmqsecretenginerole") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "rabbitmqSecretEngineRoles.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ required (printf "rabbitmqSecretEngineRoles.%s.path is required" $name) $config.path | quote }}
  {{- with $config.name }}
  name: {{ . | quote }}
  {{- end }}
  {{- with $config.tags }}
  tags: {{ . | quote }}
  {{- end }}
  {{- with $config.vhosts }}
  vhosts:
    {{- range . }}
    - vhostName: {{ required "vhosts[].vhostName is required" .vhostName | quote }}
      {{- with .permissions }}
      permissions:
        {{- if hasKey . "configure" }}
        configure: {{ .configure | quote }}
        {{- end }}
        {{- if hasKey . "read" }}
        read: {{ .read | quote }}
        {{- end }}
        {{- if hasKey . "write" }}
        write: {{ .write | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with $config.vhostTopics }}
  vhostTopics:
    {{- range . }}
    - vhostName: {{ required "vhostTopics[].vhostName is required" .vhostName | quote }}
      {{- with .topics }}
      topics:
        {{- range . }}
        - topicName: {{ .topicName | quote }}
          {{- with .permissions }}
          permissions:
            {{- if hasKey . "configure" }}
            configure: {{ .configure | quote }}
            {{- end }}
            {{- if hasKey . "read" }}
            read: {{ .read | quote }}
            {{- end }}
            {{- if hasKey . "write" }}
            write: {{ .write | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
