{{- range $name, $config := .Values.secretEngineMounts }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "secretenginemount") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "secretEngineMounts.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  type: {{ required (printf "secretEngineMounts.%s.type is required" $name) $config.type | quote }}
  {{- with $config.path }}
  path: {{ . | quote }}
  {{- end }}
  {{- with $config.description }}
  description: {{ . | quote }}
  {{- end }}
  name: {{ default $name $config.name | quote }}
  {{- $options := default (dict "version" "2") $config.options }}
  {{- with $options }}
  options:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.local }}
  local: {{ . }}
  {{- end }}
  {{- with $config.sealWrap }}
  sealWrap: {{ . }}
  {{- end }}
  {{- with $config.externalEntropyAccess }}
  externalEntropyAccess: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
