{{- range $name, $config := .Values.entities }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Entity
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "entity") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "entities.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  name: {{ default $name $config.name | quote }}
  disabled: {{ ternary $config.disabled false (hasKey $config "disabled") }}
  {{- with $config.policies }}
  policies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.metadata }}
  metadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
