{{- range $name, $config := .Values.entityAliases }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: EntityAlias
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "entityalias") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "entityAliases.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  name: {{ default $name $config.name | quote }}
  authEngineMountPath: {{ required (printf "entityAliases.%s.authEngineMountPath is required" $name) $config.authEngineMountPath | quote }}
  entityName: {{ required (printf "entityAliases.%s.entityName is required" $name) $config.entityName | quote }}
  {{- with $config.customMetadata }}
  customMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
