{{- range $name, $config := .Values.identityTokenKeys }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: IdentityTokenKey
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "identitytokenkey") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "identityTokenKeys.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  name: {{ default $name $config.name | quote }}
  algorithm: {{ default "RS256" $config.algorithm | quote }}
  rotationPeriod: {{ default "24h" $config.rotationPeriod | quote }}
  verificationTTL: {{ default "24h" $config.verificationTTL | quote }}
  {{- with $config.allowedClientIDs }}
  allowedClientIDs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
