{{- range $name, $config := .Values.identityOidcClients }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: IdentityOIDCClient
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "identityoidcclient") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "identityOidcClients.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  name: {{ default $name $config.name | quote }}
  clientType: {{ default "confidential" $config.clientType | quote }}
  key: {{ default "default" $config.key | quote }}
  accessTokenTTL: {{ default "24h" $config.accessTokenTTL | quote }}
  idTokenTTL: {{ default "24h" $config.idTokenTTL | quote }}
  {{- with $config.redirectURIs }}
  redirectURIs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.assignments }}
  assignments:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
