{{- range $name, $config := .Values.kubernetesAuthEngineConfigs }}
{{- if $config }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineConfig
metadata:
  name: {{ include "vault-config.resourceName" (dict "context" $ "resourceName" $name "resourceType" "kubernetesauthengineconfig") }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  authentication:
    path: {{ default "kubernetes" $config.authentication.path | quote }}
    role: {{ required (printf "kubernetesAuthEngineConfigs.%s.authentication.role is required" $name) $config.authentication.role | quote }}
    serviceAccount:
      name: {{ default "default" ($config.authentication.serviceAccount).name | quote }}
    {{- with $config.authentication.namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- with $config.connection }}
  connection:
    address: {{ .address | quote }}
    {{- with .maxRetries }}
    maxRetries: {{ . }}
    {{- end }}
    {{- with .timeOut }}
    timeOut: {{ . | quote }}
    {{- end }}
    {{- with .tLSConfig }}
    tLSConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  path: {{ default "kubernetes" $config.path | quote }}
  kubernetesHost: {{ default "https://kubernetes.default.svc:443" $config.kubernetesHost | quote }}
  {{- with $config.kubernetesCACert }}
  kubernetesCACert: {{ . | quote }}
  {{- end }}
  {{- with $config.PEMKeys }}
  PEMKeys:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.issuer }}
  issuer: {{ . | quote }}
  {{- end }}
  {{- with $config.disableISSValidation }}
  disableISSValidation: {{ . }}
  {{- end }}
  {{- with $config.disableLocalCAJWT }}
  disableLocalCAJWT: {{ . }}
  {{- end }}
  {{- with $config.useAnnotationsAsAliasMetadata }}
  useAnnotationsAsAliasMetadata: {{ . }}
  {{- end }}
  {{- with $config.tokenReviewerServiceAccount }}
  tokenReviewerServiceAccount:
    name: {{ .name | quote }}
  {{- end }}
  {{- with $config.name }}
  name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
